# Generated by Django 3.2.7 on 2021-10-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_zona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
